### ISSUE TITLE
RankUp not load ( Loaded a few times then stoiped loading )

### ISSUE THREAD

**Issue by Jorti1** [Falkirks/RankUp#14]
I am not sure why this happens but here is my server log 

[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] [05:41:31] [Server thread/WARNING]: Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] [05:41:31] [Server thread/INFO]: Loading pocketmine.yml...
[Server] [05:41:31] [Server thread/INFO]: Loading server properties...
[Server] [05:41:31] [Server thread/INFO]: Selected English (eng) as the base language
[Server] [05:41:31] [Server thread/INFO]: Starting Minecraft: PE server version v0.13.1 alpha
[Server] [05:41:31] [Server thread/INFO]: Opening server on 0.0.0.0:19132
[Server] [05:41:32] [Server thread/INFO]: This server is running PocketMine-MP version 1.6dev-52 "[REDACTED]" (API 1.13.1)
[Server] [05:41:32] [Server thread/INFO]: PocketMine-MP is distributed under the LGPL License
[Server] [05:41:34] [Server thread/INFO]: Loading ChestLocker v1.2
[Server] [05:41:34] [Server thread/INFO]: Loading FactionsPro v1.3.2
[Server] [05:41:34] [Server thread/INFO]: Loading SimpleAuth v1.7.1
[Server] [05:41:34] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Unknown dependency
[Server] [05:41:34] [Server thread/INFO]: Loading VoteReward v3
[Server] [05:41:34] [Server thread/INFO]: Loading Broadcaster v1.16
[Server] [05:41:34] [Server thread/INFO]: Loading CommandSigns v2
[Server] [05:41:35] [Server thread/INFO]: Loading SimpleAuthHelper v2.0.4
[Server] [05:41:35] [Server thread/INFO]: Loading VIPSlots v0.0.4
[Server] [05:41:35] [Server thread/INFO]: Loading DevTools v1.10.0
[Server] [05:41:35] [Server thread/INFO]: Loading NoVoid v0.3
[Server] [05:41:35] [Server thread/INFO]: Loading CommandTracker v1.1
[Server] [05:41:35] [Server thread/INFO]: Loading WorldEditArt v1.0.0_beta_dev_#048
[Server] [05:41:35] [Server thread/INFO]: Loading PeacefulSpawn v2.4
[Server] [05:41:35] [Server thread/INFO]: Loading BanItem v2.1
[Server] [05:41:35] [Server thread/INFO]: Loading ManyWorlds v2.0.3
[Server] [05:41:35] [Server thread/INFO]: Loading CombatLogger v1.2.0
[Server] [05:41:35] [Server thread/INFO]: Loading ClearLagg v1.1.0
[Server] [05:41:35] [Server thread/INFO]: Loading ServerMail v0.0.2
[Server] [05:41:35] [Server thread/INFO]: Loading PureGIS v1.0.0
[Server] [05:41:35] [Server thread/INFO]: Loading TimeCommander v2
[Server] [05:41:35] [Server thread/INFO]: Loading AlwaysSpawn v2.2.2
[Server] [05:41:35] [Server thread/INFO]: Loading AreaProtect v1.0.1
[Server] [05:41:35] [Server thread/INFO]: Loading SignShop v1.1.3
[Server] [05:41:35] [Server thread/INFO]: Loading ChestRefill v1.0.1
[Server] [05:41:35] [Server thread/INFO]: Loading SignStatus v3.0.0
[Server] [05:41:35] [Server thread/INFO]: Loading LimitedCreative v1.0.0
[Server] [05:41:35] [Server thread/INFO]: Loading CustomAreas v1
[Server] [05:41:35] [Server thread/INFO]: Loading KitPro v4.1
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyAPI v2.0.9
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyAuction v2.0.2
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyCasino v2.0.2
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyJob v2.0.4
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyLand v2.0.9
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyProperty v2.0.6
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyPShop v2.0.2
[Server] [05:41:35] [Server thread/INFO]: Loading EconomySell v2.0.7
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyShop v2.0.7
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyTax v2.0.3
[Server] [05:41:35] [Server thread/INFO]: Loading EconomyUsury v1.0.1
[Server] [05:41:35] [Server thread/INFO]: Loading ItemCloud v1.3
[Server] [05:41:35] [Server thread/INFO]: Loading EssentialsPE v1.1.3
[Server] [05:41:36] [Server thread/INFO]: Loading Slapper v1.2.8
[Server] [05:41:36] [Server thread/INFO]: Loading KillBounty v1.0.1.5
[Server] [05:41:36] [Server thread/INFO]: Loading EnderPearl v1.2.3
[Server] [05:41:36] [Server thread/INFO]: Loading CustomChat v5.0.0
[Server] [05:41:36] [Server thread/INFO]: [CustomChat] Loading CustomChat v_5.0.0 by Praxthisnovcht
[Server] [05:41:36] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Unknown dependency
[Server] [05:41:36] [Server thread/INFO]: Loading EconomyAirport v2.0.4
[Server] [05:41:36] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Unknown dependency
[Server] [05:41:36] [Server thread/INFO]: Loading SimpleWarp v2.1.0
[Server] [05:41:36] [Server thread/INFO]: Loading SignWarp v1.5.1
[Server] [05:41:36] [Server thread/INFO]: Loading RankUp v0.3.1
[Server] [05:41:36] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Unknown dependency
[Server] [05:41:36] [Server thread/INFO]: Loading WarpSigns v0.0.1
[Server] [05:41:36] [Server thread/INFO]: Loading SimplePortals v0.0.3
[Server] [05:41:36] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Unknown dependency
[Server] [05:41:36] [Server thread/CRITICAL]: Could not load plugin 'PocketJobs': Circular dependency detected
[Server] [05:41:41] [Server thread/INFO]: Enabling ChestLocker v1.2
[Server] [05:41:41] [Server thread/INFO]: Enabling SimpleAuth v1.7.1
[Server] [05:41:41] [Server thread/INFO]: [SimpleAuth] Everything loaded!
[Server] [05:41:41] [Server thread/INFO]: Enabling Broadcaster v1.16
[Server] [05:41:41] [Server thread/WARNING]: RuntimeException: "yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 24, column 1), context while scanning a quoted scalar (line 23, column 4)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
[Server] [05:41:41] [Server thread/INFO]: Disabling Broadcaster v1.16
[Server] [05:41:41] [Server thread/INFO]: Enabling VIPSlots v0.0.4
[Server] [05:41:41] [Server thread/INFO]: [VIPSlots] VIPSlots Enabled!
[Server] [05:41:41] [Server thread/INFO]: Enabling DevTools v1.10.0
[Server] [05:41:41] [Server thread/ERROR]: Could not load plugin 'RankUp': plugin exists
[Server] [05:41:41] [Server thread/INFO]: [DevTools] Registered folder plugin loader
[Server] [05:41:41] [Server thread/INFO]: Enabling Broadcaster v1.16
[Server] [05:41:41] [Server thread/WARNING]: RuntimeException: "yaml_parse(): scanning error encountered during parsing: found unexpected document indicator (line 24, column 1), context while scanning a quoted scalar (line 23, column 4)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
[Server] [05:41:41] [Server thread/INFO]: Disabling Broadcaster v1.16
[Server] [05:41:41] [Server thread/INFO]: Enabling CommandTracker v1.1
[Server] [05:41:41] [Server thread/INFO]: Enabling PureGIS v1.0.0
[Server] [05:41:41] [Server thread/INFO]: Enabling AlwaysSpawn v2.2.2
[Server] [05:41:41] [Server thread/INFO]: AlwaysSpawn Enabled!
[Server] [05:41:41] [Server thread/INFO]: Enabling LimitedCreative v1.0.0
[Server] [05:41:42] [Server thread/INFO]: Preparing level "MainSpawn"
[Server] [05:41:42] [Server thread/INFO]: Enabling FactionsPro v1.3.2
[Server] [05:41:42] [Server thread/INFO]: Enabling VoteReward v3
[Server] [05:41:42] [Server thread/INFO]: Enabling CommandSigns v2
[Server] [05:41:42] [Server thread/INFO]: [CommandSigns] CommandSigns Loaded!
[Server] [05:41:42] [Server thread/INFO]: Enabling SimpleAuthHelper v2.0.4
[Server] [05:41:42] [Server thread/INFO]: Enabling NoVoid v0.3
[Server] [05:41:42] [Server thread/INFO]: [NoVoid] NoVoid Loaded!
[Server] [05:41:42] [Server thread/INFO]: Enabling WorldEditArt v1.0.0_beta_dev_#048
[Server] [05:41:42] [Server thread/INFO]: Enabling PeacefulSpawn v2.4
[Server] [05:41:42] [Server thread/INFO]: Enabling BanItem v2.1
[Server] [05:41:42] [Server thread/INFO]: Enabling ManyWorlds v2.0.3
[Server] [05:41:42] [Server thread/INFO]: Enabling CombatLogger v1.2.0
[Server] [05:41:42] [Server thread/INFO]: CombatLogger enabled
[Server] [05:41:42] [Server thread/INFO]: Enabling ClearLagg v1.1.0
[Server] [05:41:42] [Server thread/INFO]: Enabling ServerMail v0.0.2
[Server] [05:41:42] [Server thread/INFO]: [ServerMail] Using ServerMailAPI found at 'phar:///storage/emulated/0/PocketMine/plugins/plugin-639.phar/src/tschrock/ServerMailAPI.php'
[Server] [05:41:42] [Server thread/INFO]: Enabling TimeCommander v2
[Server] [05:41:42] [Server thread/INFO]: Enabling AreaProtect v1.0.1
[Server] [05:41:42] [Server thread/INFO]: [AreaProtect] AreaProtect Loaded!
[Server] [05:41:42] [Server thread/INFO]: Enabling SignShop v1.1.3
[Server] [05:41:43] [Server thread/INFO]: SignShop v1.1.3 Enabled!
[Server] [05:41:43] [Server thread/INFO]: Enabling ChestRefill v1.0.1
[Server] [05:41:43] [Server thread/INFO]: Enabling SignStatus v3.0.0
[Server] [05:41:43] [Server thread/NOTICE]: [SignStatus] SignStatus loaded
[Server] [05:41:43] [Server thread/INFO]: Enabling CustomAreas v1
[Server] [05:41:43] [Server thread/INFO]: Enabling KitPro v4.1
[Server] [05:41:43] [Server thread/INFO]: Enabling EconomyAPI v2.0.9
[Server] [05:41:43] [Server thread/NOTICE]: [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] [05:41:43] [Server thread/INFO]: [EconomyAPI] Checking for updates... It may be take some while.
[Server] [05:41:48] [Server thread/NOTICE]: [EconomyAPI] 
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyAuction v2.0.2
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyCasino v2.0.2
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyJob v2.0.4
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyLand v2.0.9
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyProperty v2.0.6
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyPShop v2.0.2
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomySell v2.0.7
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyShop v2.0.7
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyTax v2.0.3
[Server] [05:41:49] [Server thread/INFO]: Enabling EconomyUsury v1.0.1
[Server] [05:41:49] [Server thread/INFO]: Enabling ItemCloud v1.3
[Server] [05:41:49] [Server thread/INFO]: Enabling EssentialsPE v1.1.3
[Server] [05:41:49] [Server thread/INFO]: [EssentialsPE] Loading...
[Server] [05:41:49] [Server thread/INFO]: Enabling Slapper v1.2.8
[Server] [05:41:50] [Server thread/INFO]: Enabling KillBounty v1.0.1.5
[Server] [05:41:50] [Server thread/INFO]: [KillBounty] Boutny Plugin Has Been Enabled!
[Server] [05:41:50] [Server thread/INFO]: Enabling EnderPearl v1.2.3
[Server] [05:41:50] [Server thread/INFO]: [EnderPearl] EnderPerl loaded!
[Server] [05:41:50] [Server thread/INFO]: Enabling CustomChat v5.0.0
[Server] [05:41:50] [Server thread/INFO]: [CustomChat] - CustomChat - Enabled!
[Server] [05:41:50] [Server thread/INFO]: Enabling EconomyAirport v2.0.4
[Server] [05:41:50] [Server thread/INFO]: Enabling SimpleWarp v2.1.0
[Server] [05:41:50] [Server thread/INFO]: [SimpleWarp] Enabling EssentialsPE support...
[Server] [05:41:50] [Server thread/INFO]: Enabling SignWarp v1.5.1
[Server] [05:41:50] [Server thread/WARNING]: [SignWarp] Disabling FastTransfer support
[Server] [05:41:50] [Server thread/INFO]: [SignWarp] enabled /xyz command
[Server] [05:41:50] [Server thread/INFO]: [SignWarp] dynamic-updates: ON
[Server] [05:41:50] [Server thread/INFO]: Enabling RankUp v0.3.1
[Server] [05:41:50] [Server thread/WARNING]: RuntimeException: "yaml_parse(): parsing error encountered during parsing: did not find expected key (line 20, column 4), context while parsing a block mapping (line 3, column 3)" (E_WARNING) in "/src/pocketmine/utils/Config" at line 143
[Server] [05:41:50] [Server thread/INFO]: Disabling RankUp v0.3.1
[Server] [05:41:50] [Server thread/INFO]: Enabling WarpSigns v0.0.1
[Server] [05:41:50] [Server thread/INFO]: Enabling SimplePortals v0.0.3
[Server] [05:41:57] [Server thread/INFO]: Starting GS4 status listener
[Server] [05:41:57] [Server thread/INFO]: Setting query port to 19132
[Server] [05:41:57] [Server thread/INFO]: Query running on 0.0.0.0:19132
[Server] [05:41:57] [Server thread/INFO]: Default game type: Survival Mode
[Server] [05:41:57] [Server thread/INFO]: Done (32.02s)! For help, type "help" or "?"
[Server] [05:41:57] [Server thread/INFO]: [ChestRefill] Chests have been reset.
[Server] [05:41:57] [Server thread/INFO]: [EssentialsPE] No new version found, you're using the latest version of EssentialsPE

**Comment by JackMD** [comment]
Update to latest version and your config.yml and/or groups.yml is not correctly parsed. Try removing them and let the plugin generate new ones. Other than that @Falkirks this issue could be closed.
