### ISSUE TITLE
how to fix this?

### ISSUE THREAD

**Issue by nooneusethisname** [Falkirks/RankUp#15]
![image](https://cloud.githubusercontent.com/assets/16216792/12373121/8cedcc6e-bca1-11e5-9694-f14ed6b9b292.png)
i have no idea why

**Comment by Falkirks** [comment]
What version of PurePerms are you running?

**Comment by nooneusethisname** [comment]
1.3.3

**Comment by JackMD** [comment]
@Falkirks the plugin is working fine now. This issue can be closed.
