### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by XShockinFireX** [Falkirks/RankUp#16]
Unhandled exception executing command 'ru' in rankup: Argument 2 passed to _64FF00\PurePerms\PurePerms::setGroup() must be an instance of _64FF00\PurePerms\PPGroup, null given, called in C:\Users\Tajwar\Corel\PocketMine-MP\plugins\RankUp-master\src\rankup\permission\PurePerms.php on line 11 and defined

InvalidArgumentException: "Argument 2 passed to _64FF00\PurePerms\PurePerms::setGroup() must be an instance of _64FF00\PurePerms\PPGroup, null given, called in C:\Users\Tajwar\Corel\PocketMine-MP\plugins\RankUp-master\src\rankup\permission\PurePerms.php on line 11 and defined" (E_RECOVERABLE_ERROR) in "/PurePerms-master/src/_64FF00/PurePerms/PurePerms" at line 639

**Comment by XShockinFireX** [comment]
plz fix

**Comment by Falkirks** [comment]
Have you created groups for the ranks in PurePerms?

**Comment by XShockinFireX** [comment]
Yep i have

**Comment by XShockinFireX** [comment]
nvm its fixed already

**Comment by XShockinFireX** [comment]
now everytime i do /unsetgperm Guest rankup.rankup it wont work players can still do /ru and /rankup

**Comment by XShockinFireX** [comment]
nvm
