### ISSUE TITLE
How to...

### ISSUE THREAD

**Issue by TeeJayPlayz** [Falkirks/RankUp#17]
Hey how do I Make is so when my players type /rankup it changes their PurePerms rank appropriately?

**Comment by TeeJayPlayz** [comment]
I made the groups but I don't know how to link them

**Comment by Falkirks** [comment]
You create groups with the name of the ranks. So if I have a rank called `A`, I should have a group called `A`.

**Comment by TeeJayPlayz** [comment]
OK I have the groups but when I type /rankup it does nothing to my pure perms group. So what do I do about that?

**Comment by TeeJayPlayz** [comment]
It just keeps crashing my served 😵

**Comment by TeeJayPlayz** [comment]
Server*
