### ISSUE TITLE
Doesn't work with PureChat

### ISSUE THREAD

**Issue by jasonwynn10** [Falkirks/RankUp#19]
The system completely breaks down and the ranks reset themselves every login. Purechat Doesn't update with the rankups.

**Comment by Jorti1** [comment]
RankUp doesn't support pureperms

**Comment by jasonwynn10** [comment]
what about purechat?

**Comment by Jorti1** [comment]
Since PureChat needs pureperms to work, basically no- I wish it supported pureperms too

**Comment by Jorti1** [comment]
You can still use ppureperms to set perms and groups tho, just set rankin the default group manager in the rankin configure file

**Comment by JackMD** [comment]
This isn't happening to me. I tested it. PureChat and PurePerm work fine.
