### ISSUE TITLE
having trouble getting it to work with pure perms

### ISSUE THREAD

**Issue by Rspuds** [Falkirks/RankUp#2]
I'm having trouble with using pure perms as the group manager. In my configs it says I can only use xperms and the one that comes with it. Does this mean my version is old and if so how do I get the most up to date. I'm sure I'm missing something easy and just don't know it. Your help would be greatly appreciated.

**Comment by Falkirks** [comment]
Change your `preferred-groupmanager` in the RankUp config to `rankup\\permission\\PurePerms`

**Comment by Rspuds** [comment]
I copyed exactly what you posted and it gave me this error as it has been probably would have been helpful to begin with but here it us now.[PocketMine] Server is starting...
[PocketMine] Server was started.
[Server] 05:18:47 [WARNING] Timezone could not be automatically determined. An incorrect timezone will result in incorrect timestamps on console logs. It has been set to "UTC" by default. You can change it on the php.ini file.
[Server] 05:18:47 [INFO] Starting Minecraft: PE server version v0.10.5 alpha
[Server] 05:18:47 [INFO] Loading pocketmine.yml...
[Server] 05:18:47 [INFO] Loading server properties...
[Server] 05:18:47 [INFO] Advanced cache enabled
[Server] 05:18:47 [INFO] Starting Minecraft PE server on 0.0.0.0:19132
[Server] 05:18:47 [INFO] This server is running PocketMine-MP version 1.4.1dev-965 "絶好(Zekkou)ケーキ(Cake)" (API 1.11.0)
[Server] 05:18:47 [INFO] PocketMine-MP is distributed under the LGPL License
[Server] 05:18:48 [INFO] Loading PurePerms v1.0.7
[Server] 05:18:48 [INFO] Loading EssentialsPE v1.0.2
[Server] 05:18:48 [INFO] Loading iProtector v3.0
[Server] 05:18:48 [INFO] Loading MineReset v2.0.3
[Server] 05:18:48 [INFO] Loading SimpleAuth v1.6.0
[Server] 05:18:48 [INFO] Loading TimeCommander v2
[Server] 05:18:48 [INFO] Loading Universe v1.0.0
[Server] 05:18:48 [INFO] [Universe] Universe Loaded!
[Server] 05:18:48 [INFO] Loading FurnaceIndicator v1.0
[Server] 05:18:48 [INFO] Loading TimeLimitCMD v0.0.1
[Server] 05:18:48 [INFO] Loading EconomyAPI v2.0.5
[Server] 05:18:48 [INFO] Loading EconomyLand v2.0.6
[Server] 05:18:48 [INFO] Loading EconomyProperty v2.0.3
[Server] 05:18:48 [INFO] Loading EconomySell v2.0.4
[Server] 05:18:48 [INFO] Loading EconomyShop v2.0.4
[Server] 05:18:48 [INFO] Loading ItemCloud v1.1
[Server] 05:18:48 [INFO] Loading EconomyPShop v2.0.0
[Server] 05:18:48 [INFO] Loading PureChat v1.2.3
[Server] 05:18:48 [INFO] Loading RankUp v0.2.1
[Server] 05:18:53 [INFO] ----- PocketMine-MP Auto Updater -----
[Server] 05:18:53 [INFO] It appears you're running a Beta build, when you've specified that you prefer to run Stable builds.
[Server] 05:18:53 [INFO] If you would like to be kept informed about new Beta or Development builds, it is recommended that you change 'preferred-channel' in your pocketmine.yml to 'beta' or 'development'.
[Server] 05:18:53 [INFO] ----- -------------------------- -----
[Server] 05:18:53 [INFO] Enabling PurePerms v1.0.7
[Server] 05:18:54 [INFO] [PurePerms] Set data provider to YAML.
[Server] 05:18:54 [INFO] Enabling SimpleAuth v1.6.0
[Server] 05:18:54 [INFO] [SimpleAuth] Everything loaded!
[Server] 05:18:54 [INFO] Enabling TimeLimitCMD v0.0.1
[Server] 05:18:54 [INFO] [TimeLimitCMD] TimeLimitCMD Initializing [...]
[Server] 05:18:54 [INFO] [TimeLimitCMD] Everything is Loaded!
[Server] 05:18:54 [INFO] Enabling PureChat v1.2.3
[Server] 05:18:54 [INFO] Preparing level "world"
[Server] 05:18:55 [INFO] Enabling EssentialsPE v1.0.2
[Server] 05:18:55 [INFO] [EssentialsPE] Loading...
[Server] 05:18:55 [INFO] Enabling iProtector v3.0
[Server] 05:18:55 [INFO] Enabling MineReset v2.0.3
[Server] 05:18:55 [INFO] Enabling TimeCommander v2
[Server] 05:18:55 [INFO] Enabling Universe v1.0.0
[Server] 05:18:55 [INFO] Enabling FurnaceIndicator v1.0
[Server] 05:18:55 [INFO] Enabling EconomyAPI v2.0.5
[Server] 05:18:55 [NOTICE] [EconomyAPI] Auto save has been set to interval : 10 min(s)
[Server] 05:18:55 [INFO] Enabling EconomyLand v2.0.6
[Server] 05:18:55 [INFO] Enabling EconomyProperty v2.0.3
[Server] 05:18:55 [INFO] Enabling EconomySell v2.0.4
[Server] 05:18:55 [INFO] Enabling EconomyShop v2.0.4
[Server] 05:18:55 [INFO] Enabling ItemCloud v1.1
[Server] 05:18:55 [INFO] Enabling EconomyPShop v2.0.0
[Server] 05:18:55 [INFO] Enabling RankUp v0.2.1
[Server] 05:18:55 [INFO] [RankUp] Loaded DoesGroups.
[Server] 
[Server] Fatal error: Class ' rankup\permission\PurePerms' not found in phar:///storage/emulated/0/PocketMine/plugins/plugin-830.phar/src/rankup/permission/PermissionLoader.php on line 15
[Server] 05:18:55 [EMERGENCY] An unrecoverable error has occurred and the server has crashed. Creating a crash dump
[Server] 05:18:55 [EMERGENCY] Please submit the "/storage/emulated/0/PocketMine/CrashDump_Wed_Mar_11-05.18.55-UTC_2015.log" file to the Bug Reporting page. Give as much info as you can.
[Server] 05:19:01 [INFO] Disabling PurePerms v1.0.7
[Server] 05:19:01 [INFO] Disabling EssentialsPE v1.0.2
[Server] 05:19:01 [INFO] Disabling iProtector v3.0
[Server] 05:19:01 [INFO] Disabling MineReset v2.0.3
[Server] 05:19:01 [INFO] Disabling SimpleAuth v1.6.0
[Server] 05:19:01 [INFO] Disabling TimeCommander v2
[Server] 05:19:01 [INFO] Disabling Universe v1.0.0
[Server] 05:19:01 [INFO] [Universe] Universe Unloaded!
[Server] 05:19:01 [INFO] Disabling FurnaceIndicator v1.0
[Server] 05:19:01 [INFO] Disabling TimeLimitCMD v0.0.1
[Server] 05:19:01 [INFO] Disabling EconomyAPI v2.0.5
[Server] 05:19:01 [INFO] Disabling EconomyLand v2.0.6
[Server] 05:19:01 [INFO] Disabling EconomyProperty v2.0.3
[Server] 05:19:01 [INFO] Disabling EconomySell v2.0.4
[Server] 05:19:01 [INFO] Disabling EconomyShop v2.0.4
[Server] 05:19:01 [INFO] Disabling ItemCloud v1.1
[Server] 05:19:01 [INFO] Disabling EconomyPShop v2.0.0
[Server] 05:19:01 [INFO] Disabling PureChat v1.2.3
[Server] 05:19:01 [INFO] Disabling RankUp v0.2.1
[Server] 05:19:01 [INFO] Unloading level "world"

**Comment by Falkirks** [comment]
Sorry, I forgot the package and release PurePerms support, I have done it now. https://github.com/Falkirks/RankUp/releases/tag/v0.3

**Comment by Rspuds** [comment]
Thanks a ton

**Comment by Rspuds** [comment]
OK sorry but I have one last question, what do I do with the files you linked me to. I tried just putting the new phar file in there and deleteing the only folder I created but it gave me to same error. So I'm guessing you have to do something with the other files on the page you linked me to but I'm not sure what.

**Comment by Falkirks** [comment]
@Rspuds That shouldn't happen. I will test this tomorrow.

**Comment by Kadin15** [comment]
Just letting you know Pocket money and economy's have both taken away the payment methods so rankup won't work so if you could please change it to work with massiveeconomys thanks I really need rank up for my prison server so could you tell me when you'll have it updated?

**Comment by Falkirks** [comment]
It takes time to add a new plugin because plugin developers tend not to fully document their APIs.

**Comment by Kadin15** [comment]
Thank you so much

**Comment by Kadin15** [comment]
And I have a question how can I make my own plugin for people to use I want to start becoming a plugin developer

**Comment by Rspuds** [comment]
Anything new on getting the plugin to work with Pure Perms?

**Comment by Kadin15** [comment]
To falls have you updated the rankup so it works with massiveeconomy?

**Comment by Falkirks** [comment]
@Kadin15 @Rspuds I haven't got a chance to make any updates. I will update here when there is progress.

**Comment by Rspuds** [comment]
OK thanks

**Comment by patrickt1220** [comment]
Any progress on this plugin with pureperms?

**Comment by Kelton01** [comment]
Yeah I did the same thing it does not work for me

**Comment by patrickt1220** [comment]
Does the built in group manager work for you?

**Comment by Kelton01** [comment]
I don't know how to use it

**Comment by Falkirks** [comment]
I will update this into a working state for 1.5 and 0.11 when 0.11 is released.

**Comment by patrickt1220** [comment]
Thank you!

**Comment by goerick** [comment]
Still when...

[20:16:28] [Server thread/CRITICAL]: Unhandled exception executing command 'rankup' in rankup: strtolower() expects parameter 1 to be string, object given
[20:16:28] [Server thread/WARNING]: InvalidArgumentException: "strtolower() expects parameter 1 to be string, object given" (E_WARNING) in "/RankUp-master/src/rankup/rank/RankStore" at line 25

**Comment by 64FF00** [comment]
@goerick @Falkirks https://github.com/Falkirks/RankUp/pull/7

**Comment by Falkirks** [comment]
@goerick This should be fixed now by #7, let me know if the issue appears again.
