### ISSUE TITLE
Rankup and PurePerms not working together

### ISSUE THREAD

**Issue by coolcrummypack** [Falkirks/RankUp#22]
So, I'm bulding my new MCPE prison server, and I would like to use rankup, and pureperms because pureperms has prefixes and such.
but whenever I test to make sure I can rankup, my whole server crashes and it creates a dump file, 
Here it is--->
Error: Call to undefined method _64FF00\PurePerms\PurePerms::getUser()
File: /RankUp_v0.3.1.phar/src/rankup/permission/PurePerms
Line: 15
Type: E_ERROR

THIS CRASH WAS CAUSED BY A PLUGIN
BAD PLUGIN: RankUp v0.3.1

Code:
[6] class PurePerms extends BasePermissionManager{
[7]     public function addToGroup(Player $player, $group){
[8]         if(!$this->checkReady()) return false;
[9]         $ppGroup = $this->getAPI()->getGroup($group);
[10]        $this->getAPI()->getUser($player)->setGroup($ppGroup, null);
[11]         return true;
[12]     }
[13]     public function getGroup(Player $player){
[14]         if(!$this->checkReady()) return false;  
[15]        $user = $this->getAPI()->getUser($player);
[16]        return $user->getGroup()->getName();
[17]     }
[18] 
[19]     /**
[20]      \* getUsers() is not implemented in PurePerms. This method will NOT work.
[21]      \* @param $name
[22]      \* @return bool|void
[23]      */
[24]     public function getPlayersInGroup($name){
[25]         if(!$this->checkReady()) return false;

Backtrace:
#0 /src/pocketmine/Server__32bit(0): pocketmine\Server->crashDump(boolean)
#1 /RankUp_v0.3.1.phar/src/rankup/rank/RankStore(39): rankup\permission\PurePerms->getGroup(boolean)
#2 /RankUp_v0.3.1.phar/src/rankup/command/RankUpCommand(19): rankup\rank\RankStore->getNextRank(boolean)
#3 /src/pocketmine/command/SimpleCommandMap(195): rankup\command\RankUpCommand->execute(boolean)
#4 /src/pocketmine/Server__32bit(1937): pocketmine\command\SimpleCommandMap->dispatch(boolean)
#5 /src/pocketmine/Player__32bit(2566): pocketmine\Server->dispatchCommand(boolean)
#6 /src/pocketmine/network/RakLibInterface(140): pocketmine\Player->handleDataPacket(boolean)
#7 /src/raklib/server/ServerHandler__32bit(90): pocketmine\network\RakLibInterface->handleEncapsulated(boolean)
#8 /src/pocketmine/network/RakLibInterface(79): raklib\server\ServerHandler->handlePacket(boolean)
#9 /src/pocketmine/network/Network__32bit(160): pocketmine\network\RakLibInterface->process(boolean)
#10 /src/pocketmine/Server__32bit(2470): pocketmine\network\Network->processInterfaces(boolean)
#11 /src/pocketmine/Server__32bit(2222): pocketmine\Server->tick(boolean)
#12 /src/pocketmine/Server__32bit(2100): pocketmine\Server->tickProcessor(boolean)
#13 /src/pocketmine/Server__32bit(1701): pocketmine\Server->start(boolean)
#14 /src/pocketmine/PocketMine(466): pocketmine\Server->__construct(boolean)
#15 (1): (boolean)
#16 (0): {main}(boolean)

It would be really nice if you can tell me whats wrong exactly, but im guessing its the code it the .phar of the rankup plugin as far as I can see.
I know you've gotten wayyyyyyy more questions about this topic but this is the one thing holding my server back so this is why Im going into detail more than others.
Thanks for reading-CCP

**Comment by Dog2puppy** [comment]
Make sure you have PureChat. I think PureChat actually adds groups.

**Comment by JackMD** [comment]
@Falkirks this is also fixed in the latest commits. After testing no such error occurs.
