### ISSUE TITLE
Trouble with preferred economy

### ISSUE THREAD

**Issue by Kelton01** [Falkirks/RankUp#3]
How do I set the preferred economy to the €conom¥$ plugin?

**Comment by Falkirks** [comment]
It should autoload if you have it installed but you can set it as preferred by setting `preferred-economy` in your config.yml to `rankup\\economy\\Economy`.

**Comment by Kelton01** [comment]
This did not work for me

**Comment by Falkirks** [comment]
What error did you get?

**Comment by Falkirks** [comment]
Also your ranks shouldn't have `$` in front of the price.

**Comment by Kelton01** [comment]
It's working now. Thanks for the help!
