### ISSUE TITLE
how to set [A] Guest ??? plz help me!!! 

### ISSUE THREAD

**Issue by HarryMyStick** [Falkirks/RankUp#30]
faction name = {fac_name}
rankup name = ????
plz help me to set this

**Comment by XDqrkneZ** [comment]
BUMP!!! @HarryMyStick have you found a fix yet!?

**Comment by ZaneWalter** [comment]
Can you be more exact maybe i could help you

**Comment by LamKietCrack** [comment]
How to give two positions example: Member [A] ?

**Comment by LamKietCrack** [comment]
How to have two Positions I Will Give an example: Member [A]

**Comment by HarryMyStick** [comment]
i have a plan and i succest to fix this now i have a prison server ><
