### ISSUE TITLE
common issue

### ISSUE THREAD

**Issue by XDqrkneZ** [Falkirks/RankUp#32]
hey, so.. I currently have Owner rank and I lose it when I /rankup. Any ideas?

**Comment by ZaneWalter** [comment]
Its complicated but its easy. Are you using RankUp with Pure Perms or RankUpDoesGroup? Either way according to be you are doing /setgroup A when you rankup and thats why you lose your Owner Group!!

**Comment by XxParkerGamesxX** [comment]
just use a suffix don't use the prefix using the prefix will change your group when you rankup so just use a suffix where it will show [Owner][A] Bajan
