### ISSUE TITLE
Feature

### ISSUE THREAD

**Issue by BroadSkate** [Falkirks/RankUp#34]
Can you add a way for people with the rank "B" for example can teleport to the "B" prison without lower ranks being able to do the same?

**Comment by Falkirks** [comment]
Isn't this already possible by adding the permissions for the commands to the `groups.yml`?

**Comment by BroadSkate** [comment]
what permission though?

**Comment by Falkirks** [comment]
The permission for the teleport command. If you are using SimpleWarps it would be `simplewarp.warp.B`

**Comment by ZaneWalter** [comment]
This is all possible i am working with it and it working like a charm

**Comment by BroadSkate** [comment]
great, thanks
