### ISSUE TITLE
Simply Not Working (Please View)

### ISSUE THREAD

**Issue by ObeyBeastJj23** [Falkirks/RankUp#36]
Rankup Command Dosent Work
On Load Up Theres An Error Message
This Is It:
[Tesseract] [02:09:19] INFO> Enabling RankUp v0.3.1

Warning: yaml_parse(): reading error encountered during parsing: invalid leading UTF-8 octet (line 1, column 1) in phar:///home/minecraft-pe-2/server/PocketMine-MP.phar/src/pocketmine/utils/Config.php on line 142

Warning: Invalid argument supplied for foreach() in phar:///home/minecraft-pe-2/server/plugins/RankUp_v0.3.1.phar/src/rankup/doesgroups/RankUpDoesGroups.php on line 58

---

This has just happened when i added some more ranks to it and now i have my server on a whitelist
Please can this be fixed asap :)

**Comment by Sandertv** [comment]
In your first added rank, do you have any unusual characters like ß or maybe even with a comma above the letter? Try removing that and restarting.

**Comment by ObeyBeastJj23** [comment]
This has thankfully solved the issue, i was using a sign for colours but have now changed it to & instead

thanks!
