### ISSUE TITLE
errors for every command, have not been able to get it to work with pureperms or economys or econemyAPI whatsoever

### ISSUE THREAD

**Issue by SourSmirnoff** [Falkirks/RankUp#37]
errors:

08.06 01:09:41 [Server] Server thread/CRITICAL Error: "Call to undefined method _64FF00\PurePerms\PurePerms::getUser()" (EXCEPTION) in "/RankUp_v0.3.1.phar/src/rankup/permission/PurePerms" at line 15 
08.06 01:09:41 [Server] Server thread/CRITICAL Unhandled exception executing command 'rankup groups' in rankup: Call to undefined method _64FF00\PurePerms\PurePerms::getUser() 

08.06 01:09:21 [Server] Server thread/CRITICAL Error: "Call to undefined method _64FF00\PurePerms\PurePerms::getUser()" (EXCEPTION) in "/RankUp_v0.3.1.phar/src/rankup/permission/PurePerms" at line 15 
08.06 01:09:21 [Server] Server thread/CRITICAL Unhandled exception executing command 'rankup b' in rankup: Call to undefined method _64FF00\PurePerms\PurePerms::getUser() 

08.06 01:08:51 [Server] Server thread/CRITICAL Error: "Call to undefined method _64FF00\PurePerms\PurePerms::getUser()" (EXCEPTION) in "/RankUp_v0.3.1.phar/src/rankup/permission/PurePerms" at line 15 
08.06 01:08:51 [Server] Server thread/CRITICAL Unhandled exception executing command 'rankup' in rankup: Call to undefined method _64FF00\PurePerms\PurePerms::getUser()

**Comment by Falkirks** [comment]
What PurePerms version are you running?

**Comment by SourSmirnoff** [comment]
PurePerms v1.4.0-INDEV

**Comment by Falkirks** [comment]
Can you download the latest build off Poggit and try? The latest release on Github won't work for that version. https://poggit.pmmp.io/ci/Falkirks/RankUp/~

**Comment by SourSmirnoff** [comment]
oddly enough, that one is not registering as a plugin in the console.

**Comment by SourSmirnoff** [comment]
is it supposed to just be named RankUp.phar

**Comment by SourSmirnoff** [comment]
ok, i did one little edit of the api, and version id and it is 100% working now! thankyou!
