### ISSUE TITLE
PurePerms still doesn't work

### ISSUE THREAD

**Issue by goerick** [Falkirks/RankUp#6]
If I  do /rankup it says it promoted me to the next group, But on purechat it still diplays my previous rank and i dont have ermissions of that group i just ranked up to.

**Comment by 64FF00** [comment]
Thats weird... I guess the getNextRank() function is broken

**Comment by 64FF00** [comment]
@Falkirks Sorry again falk, but I think I should also fix the addToGroup() function. Eheheheeheh

**Comment by Falkirks** [comment]
@64FF00 Thanks :smile:

**Comment by 64FF00** [comment]
@Falkirks :+1:

**Comment by 64FF00** [comment]
@goerick @Falkirks https://github.com/Falkirks/RankUp/pull/7

**Comment by Falkirks** [comment]
Closed by #7
