### ISSUE TITLE
When Connected On Another Group Manager.

### ISSUE THREAD

**Issue by Jefferson629** [Falkirks/RankUp#8]
When Connected On Another Group Manager Like PurePerms And xPermissions, You Always Have Enough Money To RankUp No Matter How Much You Have.

**Comment by Falkirks** [comment]
What economy are you using?

**Comment by Jefferson629** [comment]
@Falkirks I Tried Using PocketMoney And Economy$ But Still The Same... They Still Have Enough Money While I Already Set It.

**Comment by Jefferson629** [comment]
And One More Bug (I Think) When You Use PurePerms For Group Manager. Everytime You Use rankup.rankup Command It Says "An Error Have Occurred While Executing This Command." IDK  What Is The Problem In It.

**Comment by Nader6** [comment]
I have the same problem Jeffeserson629. For some reason that happens every time I try doing /rankup

**Comment by Falkirks** [comment]
@Nader6 @Jefferson629 Is any other error displayed on the console?

**Comment by Jefferson629** [comment]
@Falkirks Yes! Wait I'll Copy It Here...

**Comment by Jefferson629** [comment]
So Here It Is Sorry I Posted It Late Cuz I Got School Today.

**[Server] [03:44:38] [Server thread/CRITICAL]: Unhandled exception executing command 'rankup' in rankup: strtolower() expects parameter 1 to be string, object given
[Server] [03:44:38] [Server thread/WARNING]: InvalidArgumentException: "strtolower() expects parameter 1 to be string, object given" (E_WARNING) in "/RankUp_v0.3.phar/src/rankup/rank/RankStore" at line 25**

That Is The Error Given.

**Comment by Falkirks** [comment]
@Jefferson629 Thanks. I will look a that tomorrow. It may have slipped by v0.3.1.

**Comment by Jefferson629** [comment]
@Falkirks No Problem But Can You Also Add Prison Rank Prefix? Hehe Thnx! :D

**Comment by Jefferson629** [comment]
This Is Now Already Fixed Thnx @Falkirks!
