### ISSUE TITLE
Does not work with PurePerms still.

### ISSUE THREAD

**Issue by Nader6** [Falkirks/RankUp#9]
When I do /rankup i recieve this message:

[Server thread/CRITICAL]: Unhandled exception executing command 'rankup' in rankup: strtolower() expects parameter 1 to be string, object given
[17:55:32] [Server thread/WARNING]: InvalidArgumentException: "strtolower() expects parameter 1 to be string, object given" (E_WARNING) in "/RankUp_v0.3.phar/src/rankup/rank/RankStore" at line 25

**Comment by Falkirks** [comment]
You aren't using the latest development version. The fix will be made available in 0.3.1.

**Comment by Nader6** [comment]
So I should download the latest developmental version of pocket mine and it should work?

**Comment by Nader6** [comment]
So I should download the latest developmental version of pocket mine and it should work?

**Comment by Falkirks** [comment]
@Nader6 I am referring to the latest version of this plugin, in which @64FF00 has fixed this issue.

**Comment by Nader6** [comment]
I will download and test right now and give you my feedback @Falkirks.

**Comment by Nader6** [comment]
Oh I am sorry, has it not been released yet?

**Comment by Nader6** [comment]
I downloaded, but I do not know how to use it as a .zip file. I tried the ZipPluginLoader plugin but it didn't work. Sorry for all the trouble this is my first time being introduced to this.
